Cargo.toml
atrium-api/Cargo.toml
atrium-api/src/app/bsky/actor/defs.rs
atrium-api/src/app/bsky/embed/record.rs
atrium-api/src/app/bsky/embed/record_with_media.rs
atrium-api/src/app/bsky/feed/defs.rs
atrium-api/src/app/bsky/feed/get_post_thread.rs
atrium-api/src/app/bsky/feed/post.rs
atrium-api/src/app/bsky/richtext/facet.rs
atrium-api/src/com/atproto/admin/defs.rs
atrium-api/src/com/atproto/admin/take_moderation_action.rs
atrium-api/src/com/atproto/label/subscribe_labels.rs
atrium-api/src/com/atproto/moderation/create_report.rs
atrium-api/src/com/atproto/repo/apply_writes.rs
atrium-api/src/com/atproto/sync/subscribe_repos.rs
atrium-api/src/records.rs
atrium-codegen/src/schema.rs
atrium-codegen/src/token_stream.rs
atrium-xrpc-server/Cargo.toml
atrium-xrpc-server/src/lib.rs
atrium-xrpc-server/src/stream.rs
atrium-xrpc-server/src/stream/frames.rs
examples/firehose/Cargo.toml
examples/firehose/src/main.rs

resolves #11 
- Add `atrium-xrpc-server` member which handles message frames from subscription streams
- Add `examples/firehose`, it subscribes and prints all texts of posts
- ref: https://github.com/bluesky-social/feed-generator/blob/main/src/util/subscription.ts
- Update `codegen` and APIs for these subscription messages
https://github.com/sugyan/atrium/assets/80381/061fb8c4-4cca-4b90-9865-b642dbcd6c45

feat: Implement subscription, add firehose examples

---

atrium-api/README.md
atrium-api/src/xrpc.rs

I was unable to use `refresh_session()` and, looking around, I noticed the `atrium-xrpc` crate's [implementation](https://github.com/sugyan/atrium/blob/621865ac75defd0fad50a906ff6a0490f31e80e3/atrium-xrpc/src/lib.rs#L24) of `XrpcClient` has an `is_refresh` parameter to the `auth` method and [a corresponding way](https://github.com/sugyan/atrium/blob/621865ac75defd0fad50a906ff6a0490f31e80e3/atrium-xrpc/src/lib.rs#L48) to detect refreshes and set that parameter, enabling refreshes. I basically just copied it into the `atrium-api` version of the trait, which lets me successfully use `refresh_session()`. I don't think there's a way for `refresh_session()` to work without this.

Add `is_refresh` argument to atrium-api `XrpcClient::auth`

---

atrium-xrpc-server/src/stream/frames.rs

avoid `panic`ing unsupported frames when parsing from websocket

atrium-xrpc-server: don't panic when parsing unimplemented frames

---

atrium-xrpc/src/client/reqwest.rs
atrium-xrpc/src/lib.rs

Rename method names of XRPC traits
- `HttpClient::send` -> `send_http`
- `XrpcClient::send` -> `send_xrpc`
Having methods with the same name causes confusion when calling a method in the struct that implements them, so to avoid this, change the method name to be distinct in each trait.

Change trait method names

---

atrium-api/src/client.rs

AtpServiceWrapper only delegates `host()` to the inner xrpc client. This means that the default methods provided by the trait will be used for `auth()` and `send_xrpc()` - meaning that even if the inner struct provides one of these methods, it won't be used. Since the default method for `auth` provided by the trait always returns `None`, this breaks authentication.

Delegate to inner XrpcClient in AtpServiceWrapper

---

atrium-xrpc-server/Cargo.toml
examples/firehose/Cargo.toml
examples/firehose/src/main.rs

Updated firehose example to use `0.13` of `atrium-api` and updated endpoint to use new `bsky.network` endpoint.  As libraries have to be matched, also updated `atrium-xrpc-server` to use latest `0.13` version of `atrium-api`.

Update firehose example to latest library and endpoint

---

atrium-xrpc/src/lib.rs

Prepare for implementing endpoint switch feature for `AtpAgent`
- Change from `&str` to `String`

feat: Update return type of base_uri

---

atrium-api/src/types/integer.rs

These are necessary to get usable numeric values out of the parsed bounded types.

Add direct conversions between the Lexicon integer types and primitives

---

.github/workflows/wasm.yml

This helps to ensure no regressions occur while changes are being made to enable a WASM-compatible HTTP client to be used in `atrium-xrpc-client`.
Part of sugyan/atrium#116.

CI: Add a job to check that the `wasm32-wasi` target builds

---

.github/workflows/wasm.yml
.github/workflows/xrpc-client.yml
Cargo.lock
Cargo.toml
atrium-api/CHANGELOG.md
atrium-api/Cargo.toml
atrium-api/src/agent.rs
atrium-api/src/agent/inner.rs
atrium-api/src/agent/store.rs
atrium-api/src/agent/store/memory.rs
atrium-xrpc-client/CHANGELOG.md
atrium-xrpc-client/Cargo.toml
atrium-xrpc-client/README.md
atrium-xrpc-client/src/lib.rs
atrium-xrpc-client/src/reqwest.rs
atrium-xrpc-client/src/tests.rs
atrium-xrpc/CHANGELOG.md
atrium-xrpc/Cargo.toml
atrium-xrpc/src/lib.rs

resolve #116 
- Switch `async_trait` depending on whether `target_arch = "wasm32"` or not.
- Add tests for `wasm-pack --test`
- Tweak `atrium-xrpc-client`'s features
- Update depencencies

feat: Support wasm32

---

atrium-api/CHANGELOG.md
atrium-api/src/app/bsky/actor.rs
atrium-api/src/app/bsky/feed.rs
atrium-api/src/app/bsky/graph.rs
atrium-api/src/types.rs
lexicon/atrium-codegen/src/generator.rs
lexicon/atrium-codegen/src/lib.rs
lexicon/atrium-codegen/src/token_stream.rs

This makes operating over collections of records (such as in the repository format) easier, binding the collection NSID and record type together.

Generate structs corresponding to collections

---

Cargo.lock
Cargo.toml
atrium-cli/Cargo.toml
atrium-cli/src/bin/main.rs
atrium-cli/src/runner.rs

Commands that use `handle` by default when `actor` is not specified (e.g. `get-profile`) were panicking when called without a user logged in.
Changed to use `anyhow` to catch errors in `Runner`.

fix: Prevent panic

---

atrium-api/src/app/bsky/actor/defs.rs
atrium-api/src/com/atproto/label/defs.rs
atrium-api/src/com/atproto/server/describe_server.rs
lexicon/atrium-codegen/src/token_stream.rs

I don't think I have implemented the right solution.

Regenerating atrium-api and Dirty Fixing label/defs

---

Cargo.lock
Cargo.toml
atrium-api/Cargo.toml
atrium-api/src/types/cid_link.rs
atrium-api/src/types/string.rs
examples/firehose/Cargo.toml

- Use `ipld-core` and `serde-ipld-dagcbor` with patched branches

feat: Update dependencies

---

Cargo.lock
Cargo.toml
atrium-xrpc-client/src/isahc.rs

closes #144.
`isahc` client could handle different versions of `http` with a little workaround.

feat: Upgrade `http` crate to 1.1

---

Cargo.lock
Cargo.toml
atrium-xrpc/Cargo.toml
atrium-xrpc/src/error.rs
atrium-xrpc/src/lib.rs

fixes #160 
`serde_qs` was introduced in #25, and it did indeed correctly serialize parameters, even those that contained arrays.
However, the serialized result is a format like `uris[0]=at%3A%2F%2Fdid%3A...&uris[1]=at%3A%2F%2Fdid%3A...`, and this behavior does not seem to be changeable.
Not that this format is wrong, but it seems to cause problems when used in requests to servers that work with [`express`](https://expressjs.com/), such as bluesky's appview.
Specifically, in the `qs` library used by express, if we specify an index larger than `20` by `[]` notation, it is treated as an object key, and the query in the request is not correctly passed as an array.
https://www.npmjs.com/package/qs#parsing-arrays
It would seem that this behavior could be avoided if it could be serialized with …

feat: Replace serde_qs to serde_html_form

---

atrium-api/src/agent.rs
atrium-api/src/agent/inner.rs
atrium-api/src/types.rs

- Allows configuration of `redact` labelers header
- Make the fields of UnknownData public

feat: Update api

---

Cargo.lock
bsky-sdk/Cargo.toml
bsky-sdk/src/moderation/mutewords.rs
bsky-sdk/src/moderation/subjects/post.rs
bsky-sdk/src/moderation/tests/mutewords.rs

- Update `checkMutedWords`
- Update tests
https://github.com/bluesky-social/atproto/pull/2276

feat: Add expired/actor_target check to has_muted_word

---

atrium-api/CHANGELOG.md
atrium-api/src/types/string.rs

The `AsRef` implementation exposes the `chrono::DateTime`, so we need a different API to expose the canonical serialized form. It can be accessed via `serde::Serialize` but that forces a copy which may be unnecessary in some situations.

api: Add `Datetime::as_str`

---

Cargo.lock
Cargo.toml

The latest ATProto update completely broke our client because `gzip` was not enabled...
I'm not sure, but I think it was caused by [this PR](https://github.com/bluesky-social/atproto/pull/2770) since everything started to error around the time it was merged.
Example of broken endpoint: `app.bsky.feed.getAuthorFeed`
It seems that all we have to do for `reqwest` is enable a feature flag, but we need to check if `isahc` is working or not, and quickly implement a fix if it's not. This is very high priority. I can't finish it right now since it's very late and I'm about to go to sleep...
@sugyan, I'm not sure if I'll be awake when you see this, so feel free to work on this yourself, if you have to. I'm giving you access to [my fork of atrium](https://github.com/oestradiol/atrium) just in case, …

fix: Enabling gzip for request body decompression

---

atrium-api/src/types/string.rs

The several Regex expressions used for validating types such as DateTime and DID are compiled individually during each deserialization. When profiling an application consuming thousands of events a second (firehose), these account for nearly 50% of CPU time.

Replace OnceCell with static OnceLock for regex compilation

---

bsky-sdk/README.md

Adds an example to the README in the `bsky-sdk`. This is often the first thing new users will want to try when interacting with the SDK.

doc: Add example of how to create a Post on bsky

---

Cargo.lock
atrium-oauth/oauth-client/Cargo.toml
atrium-oauth/oauth-client/examples/main.rs
atrium-oauth/oauth-client/src/atproto.rs
atrium-oauth/oauth-client/src/http_client/dpop.rs
atrium-oauth/oauth-client/src/lib.rs
atrium-oauth/oauth-client/src/oauth_client.rs
atrium-oauth/oauth-client/src/server_agent.rs
atrium-oauth/oauth-client/src/types.rs
atrium-oauth/oauth-client/src/types/request.rs

- Update `atproto::AtprotoLocalhostClientMetadata`
- Make `redirect_uri` and `scope` configurable
- Add tests
- Update `DpopClient`
- Include `ath` in the proof when access_token is set in the `Authorization` header of the request
- Improved judgment process of `is_use_dpop_nonce_error` method
- Remove unused fields
- Add request parameters for refresh token

feat: Update oauth_client

---

examples/firehose/Cargo.toml
examples/firehose/src/cid_compat.rs
examples/firehose/src/lib.rs
examples/firehose/src/main.rs

the `firehose` example currently transitively has dependencies on two versions of `cid`: `v0.10.1` and `v0.11.1`, which have different types for `Cid`. 
This PR doesn't fix the root issue (haven't had the time to drill down), but adds a newtype + a dependency on the example to convert from the old cid to the new cid. 
It's merely a band-aid but I think it's important to keep examples working, as it is a great way of getting started. 
Thanks a lot for the library btw :)

Fix firehose example

---

atrium-oauth/oauth-client/src/atproto.rs

According to https://atproto.com/specs/oauth this field is optional.

make `AtprotoClientMetadata`'s `client_uri` optional

---

Cargo.lock
Cargo.toml
examples/concurrent/Cargo.toml
examples/firehose/Cargo.toml
examples/firehose/src/stream/frames.rs
examples/rust-toolchain.toml
examples/video/Cargo.toml

Based on [this discussion](https://github.com/sugyan/atrium/pull/272#discussion_r1921560066).
It's hard to keep examples up-to-date with the current state of the repository because they are explicitly targeting the last released version.
However, it's fairly trivial for users to discover the examples for a particular release by looking at the git tags.
Given that, it seems reasonable to just add the examples to the workspace and direct users to use git tags to discover the examples for the previous release.

chore: Add examples to workspace

---

atrium-api/src/types/string.rs

This simply adds some new `Tid` convenience constructors so that users do not have to write their own if they want to construct a timestamp.

feat: Add `Tid::now` and `Tid::from_datetime` constructors

---

Cargo.lock
Cargo.toml
atrium-api/Cargo.toml
atrium-api/README.md
atrium-api/src/agent.rs
atrium-api/src/agent/atp_agent.rs
atrium-api/src/agent/atp_agent/inner.rs
atrium-api/src/agent/atp_agent/store.rs
atrium-api/src/agent/inner.rs
atrium-api/src/agent/session_manager.rs
atrium-api/src/agent/utils.rs
atrium-xrpc/src/error.rs
atrium-xrpc/src/traits.rs
bsky-sdk/Cargo.toml
bsky-sdk/src/agent.rs
bsky-sdk/src/agent/builder.rs
bsky-sdk/src/agent/config.rs
bsky-sdk/src/record.rs
bsky-sdk/src/record/agent.rs
bsky-sdk/src/rich_text.rs
examples/concurrent/src/main.rs
examples/video/src/main.rs

Extracted from #243 only the parts that are really related to `atrium_api::Agent`.
- Add `SessionManager` trait in preparation for `OAuthSession` addition.
- Add `Agent` struct created from `SessionManager`.
- Move `AtpAgent` as a wrapper for `Agent` created from `CredentialSession`
- `bsky-sdk` was also modified with the above changes.

feat: Agent rework

---

examples/firehose/src/main.rs
examples/firehose/src/subscription.rs

The example previously treated some websocket control frames (e.g. pings) as a signal to exit.
When listening from a low volume PDS, this meant that the example would frequently exit if no activity was occurring.

chore: Improve the robustness of the firehose consumer example

---

Cargo.lock
Cargo.toml
bsky-sdk/Cargo.toml

The build is failing because `idna_adapter 1.2.1` is now MSRV `v1.82.0`.
https://crates.io/crates/idna_adapter/1.2.1
https://github.com/atrium-rs/atrium/actions/runs/15243312262/job/42866108279#step:4:349
---
This pull request introduces a new dependency, `idna_adapter`, to the project and updates its usage in the workspace configuration. The changes ensure consistency across the dependency management files.
* Added `idna_adapter = "=1.2.0"` to the dependencies in `Cargo.toml` to include the new library in the project.
* Updated the workspace configuration in `bsky-sdk/Cargo.toml` to include `idna_adapter` while maintaining `native-tls` and other dependencies.

fix: Update Cargo.toml for pinning version of dependencies
