.github/workflows/release-plz.yml, release-plz.toml
https://github.com/MarcoIeni/release-plz
=> Add release-plz

atrium-xrpc-server/Cargo.toml, atrium-xrpc-server/src/stream/frames.rs, examples/firehose/src/main.rs
=> feat: Use `anyhow::Error` for supporting `Send + Sync + 'static`

.github/workflows/xrpc.yml, atrium-xrpc/Cargo.toml, atrium-xrpc/README.md, atrium-xrpc/src/error.rs, atrium-xrpc/src/lib.rs, atrium-xrpc/src/reqwest.rs, release-plz.toml
- move `xrpc` definitions from `api`
- ready to publish
=> feat: xrpc

atrium-xrpc/README.md, atrium-xrpc/src/client.rs, atrium-xrpc/src/client/reqwest.rs, atrium-xrpc/src/error.rs, atrium-xrpc/src/lib.rs
- Update `XrpcClient` interface
- Add `Error` types
- Remove re-export `http`
- Add tests
- Update docs
=> feat: update xrpc interfaces

atrium-codegen/src/schema.rs, atrium-codegen/src/token_stream.rs, atrium-lex/src/lexicon.rs
ref: https://github.com/bluesky-social/atproto/pull/1628
=> feat(lex): Enforce properties field on LexObject

atrium-xrpc/Cargo.toml, atrium-xrpc/src/lib.rs
- Add types `XrpcRequest` and `XrpcResult`
- Add `Send + Sync` to all parameters of `send_xrpc`
=> Update XRPC interface

.github/workflows/xrpc-client.yml, Cargo.toml, atrium-xrpc-client/Cargo.toml, atrium-xrpc-client/README.md, atrium-xrpc-client/src/isahc.rs, atrium-xrpc-client/src/lib.rs, atrium-xrpc-client/src/reqwest.rs, atrium-xrpc-client/src/surf.rs, atrium-xrpc-client/src/tests.rs, release-plz.toml
Add `atrium-xrpc-client` package.
resolves #39
=> feat: Add xrpc-client package

atrium-api/Cargo.toml, atrium-api/README.md, atrium-api/src/agent.rs, atrium-api/src/com/atproto/admin/defs.rs, atrium-api/src/com/atproto/server/get_session.rs
https://github.com/bluesky-social/atproto/commit/697f5d36270f05891167b81a98e4c55cef3c1210
=> feat: Update API, based on the latest lexicon schemas

atrium-api/src/com/atproto/repo/describe_repo.rs, atrium-api/src/com/atproto/server/create_account.rs, atrium-api/src/com/atproto/server/create_session.rs, atrium-api/src/com/atproto/server/get_session.rs, atrium-api/src/com/atproto/server/refresh_session.rs, atrium-api/src/did_doc.rs, atrium-api/src/lib.rs, atrium-codegen/src/token_stream.rs
ref: https://github.com/bluesky-social/atproto/discussions/1510
- Add `did_doc` to api
- Update codegen
=> fix: Add DidDocument

atrium-xrpc-client/Cargo.toml, atrium-xrpc-client/src/isahc.rs, atrium-xrpc-client/src/reqwest.rs, atrium-xrpc-client/src/surf.rs
- Update `atrium-xrpc` version to `0.8.0`
- Fix clients
=> feat(xrpc-client): Update xrpc version, fix base_uri

atrium-api/Cargo.toml, atrium-api/src/agent.rs
- Update dependency versions
- Update AtpAgent
=> feat(api): Update xrpc and xrpc-client version

atrium-xrpc-server/Cargo.toml, examples/firehose/Cargo.toml, examples/firehose/src/main.rs
Also add blocks for error handling - note that some `post` creation messages fail to deserialize - is that what #17 covers?
=> Update firehose example to latest atrium-api library

atrium-api/src/agent/inner.rs, atrium-api/src/agent/store/memory.rs, atrium-xrpc/src/error.rs, atrium-xrpc/src/traits.rs, bsky-sdk/src/agent.rs, bsky-sdk/src/agent/builder.rs, bsky-sdk/src/error.rs, bsky-sdk/src/preference.rs
- Add `Clone` to `BskyAgent`, `Preferences`.
- Add `Debug` to XRPC errors.
=> feat: Add `Clone` and `Debug`

atrium-xrpc-client/src/isahc.rs, atrium-xrpc-client/src/reqwest.rs
=> fix: Remove `Arc` from xrpc-clients

atrium-api/src/types.rs
`Ipld::Link` should be serialized as `CidLink`.
=> fix: Fix serialization of Unknown(DataModel)

atrium-api/src/types.rs
=> fix: Add more fix to serialize_data_model

bsky-sdk/src/error.rs, bsky-sdk/src/lib.rs
=> fix: Make bsky_sdk::error public

release-plz.toml
CHANGELOG of each package will be automatically generated by `release-plz`.
https://release-plz.ieni.dev/docs/changelog
Override this format to display author names.
Hopefully, a better format can be made, but this may be possible as ongoing features are released.
https://github.com/MarcoIeni/release-plz/pull/1635
=> chore: Update release-plz.toml

atrium-api/src/did_doc.rs
New methods:
* get_feed_gen_endpoint
* get_notif_endpoint
* get_signing_key
=> feat: Extend DidDocument with useful methods

README.md
=> Add rsky link
